Create TRIGGER tg_DelVenta
ON Venta_Derivada
AFTER  DELETE
AS
	BEGIN
		Declare @Id_venta					Int,
				@Id_VentaWeb				Int,
				@Serie_Boleto				SmallInt,
				@Numero_Boleto				Int,
				@Tipo						Char(1),
				@Codi_Empresa				Tinyint,
				@FechaViaje					Varchar(10),
				@FechaVenta					Varchar(10),
				@FechaRegistro				SmallDatetime,
				@HoraProgamacion			Varchar(10),
				@HoraViaje					Varchar(10),
				@HoraEmbarque				Varchar(10),
				@Codi_programacion			Int,
				@Codi_Usuario				SmallInt,
				@Codi_Origen				SmallInt,
				@Codi_Destino				SmallInt,
				@Codi_Servicio				Tinyint,
				@Codi_Embarque				SmallInt,
				@Codi_Arribo				SmallInt,
				@Precio						Real,
				@Pasajero					Varchar(200),
				@Dni						Varchar(20),
				@Ruc						Varchar(11),
				@Asiento					Tinyint,
				@Indi_Anulado				VarChar(3),
				@Fecha_Anulacion			SmallDatetime,
				@Codi_Usuario_Anu			SmallInt,
				@Flag_Venta					Varchar(3),
				@Codi_Sucursal				SmallInt,
				@Codi_PuntoVenta			SmallInt,
				@TipoMovimiento				Varchar(200)

		Select 
		@Id_venta			=	DELETED.id_venta,
		@FechaViaje			=	Convert(Varchar(10),DELETED.Fecha_Viaje,103),
		@HoraViaje			=	DELETED.Hora_Viaje,
		@HoraEmbarque		=	DELETED.Hora_Embarque_Web,
		@Codi_Servicio		=	DELETED.Servicio,
		@Codi_Embarque		=	DELETED.Sube_En,
		@Codi_Arribo		=	DELETED.baja_en
		from DELETED 

		Select Top 1
		@Id_VentaWeb		=	Tb_Auditoria_Venta.Id_VentaWeb,		
		@Serie_Boleto		=	Tb_Auditoria_Venta.Serie_Boleto,		
		@Numero_Boleto		=	Tb_Auditoria_Venta.Numero_Boleto,		
		@Tipo				=	Tb_Auditoria_Venta.Tipo,				
		@Codi_Empresa		=	Tb_Auditoria_Venta.Codi_Empresa,		
		@FechaVenta			=	Tb_Auditoria_Venta.FechaVenta,			
		@HoraProgamacion	=	Tb_Auditoria_Venta.HoraProgamacion,
		@Codi_programacion	=	Tb_Auditoria_Venta.Codi_programacion,	
		@Codi_Usuario		=	Tb_Auditoria_Venta.Codi_Usuario,		
		@Codi_Origen		=	Tb_Auditoria_Venta.Codi_Origen,		
		@Codi_Destino		=	Tb_Auditoria_Venta.Codi_Destino,		
		@Precio				=	Tb_Auditoria_Venta.Precio,				
		@Pasajero			=	Tb_Auditoria_Venta.Pasajero,			
		@Dni				=	Tb_Auditoria_Venta.Dni,				
		@Ruc				=	Tb_Auditoria_Venta.Ruc,				
		@Asiento			=	Tb_Auditoria_Venta.Asiento,			
		@Indi_Anulado		=	Tb_Auditoria_Venta.Indi_Anulado,		
		@Fecha_Anulacion	=	Tb_Auditoria_Venta.Fecha_Anulacion,	
		@Codi_Usuario_Anu	=	Tb_Auditoria_Venta.Codi_Usuario_Anu,	
		@Flag_Venta			=	Tb_Auditoria_Venta.Flag_Venta,			
		@Codi_Sucursal		=	Tb_Auditoria_Venta.Codi_Sucursal,		
		@Codi_PuntoVenta	=	Tb_Auditoria_Venta.Codi_PuntoVenta,	
		@TipoMovimiento		=	'Eliminacion'
		from Tb_Auditoria_Venta	Where id_venta=@Id_venta
		Order By FechaRegistro Desc

		
		Insert Into Tb_Auditoria_Venta
		(
			Id_venta			,
			Id_VentaWeb			,
			Serie_Boleto		,
			Numero_Boleto		,
			Tipo				,
			Codi_Empresa		,
			FechaViaje			,
			FechaVenta			,
			FechaRegistro		,
			HoraProgamacion		,
			HoraViaje			,
			HoraEmbarque		,
			Codi_programacion	,
			Codi_Usuario		,
			Codi_Origen			,
			Codi_Destino		,
			Codi_Servicio		,
			Codi_Embarque		,
			Codi_Arribo			,
			Precio				,
			Pasajero			,
			Dni					,
			Ruc					,
			Asiento				,
			Indi_Anulado		,
			Fecha_Anulacion		,
			Codi_Usuario_Anu	,
			Flag_Venta			,
			Codi_Sucursal		,
			Codi_PuntoVenta		,
			TipoMovimiento		
		)
		Values
		(
			@Id_venta			,
			@Id_VentaWeb		,
			@Serie_Boleto		,
			@Numero_Boleto		,
			@Tipo				,
			@Codi_Empresa		,
			@FechaViaje			,
			@FechaVenta			,
			getdate()			,
			@HoraProgamacion	,
			@HoraViaje			,
			@HoraEmbarque		,
			@Codi_programacion	,
			@Codi_Usuario		,
			@Codi_Origen		,
			@Codi_Destino		,
			@Codi_Servicio		,
			@Codi_Embarque		,
			@Codi_Arribo		,
			@Precio				,
			@Pasajero			,
			@Dni				,
			@Ruc				,
			@Asiento			,
			@Indi_Anulado		,
			@Fecha_Anulacion	,
			@Codi_Usuario_Anu	,
			@Flag_Venta			,
			@Codi_Sucursal		,
			@Codi_PuntoVenta	,
			@TipoMovimiento
		)
	END