GO
IF EXISTS (SELECT Top 1 1 FROM sys.objects WHERE type = 'P' AND name = 'TB_COMPRAS_WEB_INSERT')
	BEGIN
		DROP PROCEDURE TB_COMPRAS_WEB_INSERT
	End
GO
GO
Create PROCEDURE TB_COMPRAS_WEB_INSERT
@CODI_PROGRAMACION INT,  
@ID_ORDEN          INT, 
@NUME_ASIENTO      INT,
@ORIGEN            INT,
@DESTINO           INT,
@NOMBRE            VARCHAR(100),
@DNI               VARCHAR(10),
@NRO_VIAJE         INT,
@FECHA             varchar(30),
@SERVICIO          INT, 	
@HORA              VARCHAR(100),
@IMPORTE            NUMERIC(15,2)		
AS
BEGIN	

	INSERT INTO TB_COMPRAS_WEB		
	(CODI_PROGRAMACION,ID_ORDEN,NUME_ASIENTO,ORIGEN,DESTINO,NOMBRE,DNI,NRO_VIAJE,FECHA,SERVICIO,HORA,IMPORTE)
	VALUES
	(@CODI_PROGRAMACION,@ID_ORDEN,@NUME_ASIENTO,@ORIGEN,@DESTINO,@NOMBRE,@DNI,@NRO_VIAJE,@FECHA,@SERVICIO,@HORA,@IMPORTE)	

END