Create Table Tb_Auditoria_Venta(
Id_venta			Int,
Id_VentaWeb			Int,
Serie_Boleto		SmallInt,
Numero_Boleto		Int,
Tipo				Char(1),
Codi_Empresa		Tinyint,
FechaViaje			Varchar(10),
FechaVenta			Varchar(10),
FechaRegistro		SmallDatetime,
HoraProgamacion		Varchar(10),
HoraViaje			Varchar(10),
HoraEmbarque		Varchar(10),
Codi_programacion	Int,
Codi_Usuario		SmallInt,
Codi_Origen			SmallInt,
Codi_Destino		SmallInt,
Codi_Servicio		Tinyint,
Codi_Embarque		SmallInt,
Codi_Arribo			SmallInt,
Precio				Real,
Pasajero			Varchar(200),
Dni					Varchar(20),
Ruc					Varchar(11),
Asiento				Tinyint,
Indi_Anulado		VarChar(3),
Fecha_Anulacion		SmallDatetime,
Codi_Usuario_Anu	SmallInt,
Flag_Venta			Varchar(3),
Codi_Sucursal		SmallInt,
Codi_PuntoVenta		SmallInt,
TipoMovimiento		Varchar(200)
)


sp_help tb_programacion