Create Table Tb_BoletoRuta(
BoletoRutaId		BigInt	Primary Key Identity,
Codi_Programacion	Int,
Codi_Empresa		Tinyint,
Fecha_Venta			Smalldatetime,
Fecha_Liquidacion	Smalldatetime,
Fecha_Viaje			Smalldatetime,
Codi_Boletero		Varchar(10),
Codi_Origen			SmallInt,--Origen Pasajero
Codi_Destino		SmallInt,--Destino Pasajero
Codi_Sucursal		Smallint,
Codi_PuntoVenta		Smallint,
TipoDoc				SmallInt,
Serie				Varchar(6),
Numero				BigInt,
Exonerado			Real,
ValorVenta			Real,
IGV					Real,
Total				Real,
Anulado				Char(1),
Fecha_Anulacion		Smalldatetime,
EstadoBoleto		Char(1),
TD_Pasajero			Tinyint,
ND_Pasajero			Varchar(15),
Nom_Pasajero		Varchar(100),
AP_Pasajero			Varchar(100),
AM_Pasajero			Varchar(100),
Sexo				Char(1),
Ruc_Pasajero		Varchar(11),
Nro_Asiento			SmallInt,
Imp_Manifiesto		Varchar(4),
Control				Tinyint,
Tipo				Char(1)
)
